"""empty message

Revision ID: 0a5d6d0ebd17
Revises: f0b5e99be54a
Create Date: 2024-08-02 20:11:37.372485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5d6d0ebd17'
down_revision = 'f0b5e99be54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('feature')

    # ### end Alembic commands ###
