"""empty message

Revision ID: 2aff17f50e00
Revises: 4f0fe64a315d
Create Date: 2024-07-20 16:31:43.675961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aff17f50e00'
down_revision = '4f0fe64a315d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine', sa.String(length=100), nullable=True))
        batch_op.drop_column('volume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.FLOAT(), nullable=True))
        batch_op.drop_column('engine')

    # ### end Alembic commands ###
