"""empty message

Revision ID: 4218816da831
Revises: 2aff17f50e00
Create Date: 2024-08-02 15:21:28.700075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4218816da831'
down_revision = '2aff17f50e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('transmission',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('transmission',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
