"""empty message

Revision ID: c7b75a0a39e3
Revises: 0a5d6d0ebd17
Create Date: 2024-08-02 20:19:51.123201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b75a0a39e3'
down_revision = '0a5d6d0ebd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('luxury', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comfort', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reliability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quality', sa.String(length=100), nullable=True))
        batch_op.drop_column('feature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('quality')
        batch_op.drop_column('reliability')
        batch_op.drop_column('comfort')
        batch_op.drop_column('luxury')

    # ### end Alembic commands ###
