"""empty message

Revision ID: dd4657fe1324
Revises: c7b75a0a39e3
Create Date: 2024-08-04 12:39:34.874654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4657fe1324'
down_revision = 'c7b75a0a39e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('feature2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('feature3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('feature4', sa.String(length=100), nullable=True))
        batch_op.drop_column('comfort')
        batch_op.drop_column('quality')
        batch_op.drop_column('reliability')
        batch_op.drop_column('luxury')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('luxury', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reliability', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('quality', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('comfort', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('feature4')
        batch_op.drop_column('feature3')
        batch_op.drop_column('feature2')
        batch_op.drop_column('feature1')

    # ### end Alembic commands ###
